name: Build IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cordova
        run: npm install -g cordova
      - name: Create Project
        run: |
          cordova create build com.mygta GTA62
          cd build
          cordova platform add ios
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="refresh" content="0; url=https://gta62.lovable.app"></head><body style="background: black;"></body></html>' > www/index.html
      - name: Build IPA
        run: |
          cd build
          cordova build ios --no-sign
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-ipa
          path: build/platforms/ios/build/device/*.ipa
